### ISSUE TITLE
Getting SignerValidateException

### ISSUE THREAD

**Issue by dpschen** [hitrov/oci-arm-host-capacity#1]
Hello 👋 ,
when I run the script I get this exception:

```sh
php /home/ubuntu/oci-arm-host-capacity/index.php
PHP Fatal error:  Uncaught Hitrov\OCI\Exception\SignerValidateException: URL is invalid: https://iaas..oraclecloud.com/20160918/instances/?availabilityDomain=&compartmentId= in /home/ubuntu/oci-arm-host-capacity/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php:329
Stack trace:
#0 /home/ubuntu/oci-arm-host-capacity/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php(67): Hitrov\OCI\Signer->validateParameters()
#1 /home/ubuntu/oci-arm-host-capacity/src/OciApi.php(111): Hitrov\OCI\Signer->getHeaders()
#2 /home/ubuntu/oci-arm-host-capacity/index.php(34): Hitrov\OciApi->getInstances()
#3 {main}
  thrown in /home/ubuntu/oci-arm-host-capacity/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php on line 329
  ```

I guess that I made some mistake in declaring the key file path (aka `OCI_PRIVATE_KEY_FILENAME`), but I can't figure out what exactly I did wrong.

(Also sorry for posting this issue initially empty, I clicked publish before being finished by accident)

**Comment by hitrov** [comment]
hi,
I've just cloned the repo in temp dir, run composer install.
adjusted values in constructor (only there).
and set SSH key with env var before running the script.
it's working.

I see that for some reason you have URL with two dots, why's that? 

![Снимок экрана 2021-08-04 в 21 33 41](https://user-images.githubusercontent.com/26094610/128236050-9188b627-6a58-4a1b-bdc9-8477223d438b.png)
![Снимок экрана 2021-08-04 в 21 33 32](https://user-images.githubusercontent.com/26094610/128236061-50da7934-f584-4ffd-9a8d-85194710ee93.png)

**Comment by dpschen** [comment]
hi :),

Thanks for the quick answer.
I guess I found out why it didn't work:
I was following the README and was confused by the new introduced env vars for the test (intruduced [here](https://github.com/hitrov/oci-arm-host-capacity/commit/e1830165131f3e3d00673427b0a734781da5240e#diff-7413d6453f901e939bbd840c8f0d1c7b20c2ca0e7f71741e4e07c6cf036f16c0R11-R20)).

After I filled out the data like only with strings (so without the `getenv(...) ??`) I get now:

```sh
Already have an instance(s) [] in state(s) (respectively) []. User: 'ocid1.user.oc1..aaaaaaaa***'
```

**Comment by dpschen** [comment]
Okay. After removing the `getenv(...) ??` everywhere (and filling in the data like discribed in the README I get now:

```sh
{
    "code": "InternalError",
    "message": "Out of host capacity."
}
```

That sound's already better 👍

**Comment by hitrov** [comment]
btw I fixed one issue because of your attention, so thanks as well=)
https://github.com/hitrov/oci-arm-host-capacity/commit/5c7cb7a371bb8fa0066168558f45831fa8ce4900

it was related to edge case when you have falsy value as env var value of max instances.

**Comment by hitrov** [comment]
@dpschen I see that it also caused an issue with $shape var, because now I don't have empty names for instances which I already have :) 
![Снимок экрана 2021-08-04 в 22 02 12](https://user-images.githubusercontent.com/26094610/128239714-694fd440-84ed-47e8-ad38-3552959153e6.png)

**Comment by dpschen** [comment]
Thanks for the help :)
Seems to be running now. Let's hope I get lucky 🎉

**Comment by dpschen** [comment]
It worked! :) Thanks so much!!
