### ISSUE TITLE
Process dies after 3 attempts

### ISSUE THREAD

**Issue by brian6932** [hitrov/oci-arm-host-capacity#103]
![image](https://github.com/hitrov/oci-arm-host-capacity/assets/18603393/9bb02901-4693-48de-b59d-e9dfdc69f778)
Am I missing something? Not a big deal since I can just wrap it in a `for(;;) {}`, but definitely seems unintended.

**Comment by hitrov** [comment]
Process finishes after trying all availability domains within the region. Setup cron running every 5 min. I don’t recommend more often schedule

**Comment by brian6932** [comment]
Ah I see, I'll setup an interval every 5 mins, thanks 👍
