### ISSUE TITLE
is it possible to put boot volume ocid instead of image id?

### ISSUE THREAD

**Issue by jason8098** [hitrov/oci-arm-host-capacity#11]
is it possible to put boot volume ocid instead of image id?

**Comment by hitrov** [comment]
hi, I'd say yes but you need to how exactly it should look. so:

- copy general "image" JSON request from dev tools
- execute creation using boot volume instead (and copy it the same was as above)
- if JSONs are minified, beatify them https://codebeautify.org/jsonviewer
- compare two those JSONs using e.g. https://www.diffchecker.com 
- slightly modify JSON request here https://github.com/hitrov/oci-arm-host-capacity/blob/main/src/OciApi.php#L51 for your needs

**Comment by hitrov** [comment]
that's a more rare use case so I didn't want to overcomplicate this particular script.
but maybe I'll have some time in the future and introduce this. as well as boot volume size adjustment

**Comment by hitrov** [comment]
actually, I've done it=) https://github.com/hitrov/oci-arm-host-capacity/pull/12 @jason8098

**Comment by jason8098** [comment]
@hitrov Thank a lot man! ♡
