### ISSUE TITLE
why notifications not work

### ISSUE THREAD

**Issue by MuRuLOSE** [hitrov/oci-arm-host-capacity#111]
I specified TELEGRAM_BOT_API_KEY and TELEGRAM_USER_ID in .env

but it doesn't work, the token is correct, the user id is correct.

Here are the contents of .env:

```env
TELEGRAM_BOT_API_KEY="TOKEN"
TELEGRAM_USER_ID=1234567890
...
```

what's wrong?

**Comment by hitrov** [comment]
I guess you haven’t started a conversation with your bot

**Comment by MuRuLOSE** [comment]
> I guess you haven’t started a conversation with your bot

 I started conservation with a bot, but it doesn't work

**Comment by MuRuLOSE** [comment]
> I guess you haven’t started a conversation with your bot

 I started conservation with a bot, but it doesn't work

**Comment by hitrov** [comment]
Message is sent only when instance was created successfully. Was that a case?
