### ISSUE TITLE
Script stops after 3rd request?

### ISSUE THREAD

**Issue by Karelak** [hitrov/oci-arm-host-capacity#119]
[Karelka@DESKTOP-FMDRDA7 oci-arm-host-capacity]$ php index.php
{
    "code": "InternalError",
    "message": "Out of host capacity."
}
{
    "code": "InternalError",
    "message": "Out of host capacity."
}
{
    "code": "NotAuthorizedOrNotFound",
    "message": "shape VM.Standard.A1.Flex not found"
}

I will send any files if need be

**Comment by Karelak** [comment]
Thanks, I think I figured out the other problem with it as well. Seems like AD3 does not actually have a1.flex, only ad1 and ad2

**Comment by prono69** [comment]
Hey @Karelak just asking, you got the vps or this script is still running?

**Comment by Karelak** [comment]
> Hey @Karelak just asking, you got the vps or this script is still running?

Yeah it is still running on a vps. I just made a from job to run it. Really hasn't worked as well it's been a month and I just keep getting out of host capacity

**Comment by Karelak** [comment]
OK so i got the server after about 1.5 months. I lost ssh keys lol so i found this video in case someone also has the same problem. Very easy with it:
https://youtu.be/rQlKDMnGynk?si=nXCUJs1cJn4oGvnF
Also another useful thing you can do is make it so you can use all the space available and this video shows how to do that:
https://youtu.be/xO_eef6DbnA?si=-tma6lW4wsGUNBAA

**Comment by prono69** [comment]
@Karelak is 5 minutes interval is safe ? Or should I use 10 or 15 minutes interval?
How much time interval you used ?

**Comment by guhanmathi** [comment]
@Karelak, Thank you, I fetched the availability domain from the chrome developer tool inspect instance and then used the following in the index.php to avoid similar errors 

`    getenv('OCI_AVAILABILITY_DOMAIN') ?: ["JKjj:UK-LONDON-1-AD-3","JKjj:UK-LONDON-1-AD-1"] ,`
