### ISSUE TITLE
Parsing error at dotenv file.

### ISSUE THREAD

**Issue by elterrasense** [hitrov/oci-arm-host-capacity#16]
Hello, I was trying to run this script with all setup, but when I tried to execute it i get the following error:

![WindowsTerminal_155922_25012022](https://user-images.githubusercontent.com/19367314/151001229-47e684d0-5f10-4e67-b9a7-63939f05ee39.png)

Looks like an error parsing the .pem file somehow. I cloned the git less than a week ago so I don't think it's outdated. Any help?

By the way, as an important side note, I used Firefox on Windows for the process of copying the curl for the instance, and the error you have to copy is different, it's a 500 error that looks like this, also on the Network tab:
![firefox_160242_25012022](https://user-images.githubusercontent.com/19367314/151001992-f2f2cc77-a590-45d4-9152-a170e3d2d4d6.png)

Thanks!

**Comment by hitrov** [comment]
Hey. Looks like it works a bit different on Windows, I don’t have a PC to check. Suggest you to upload inside the Object Storage and “create pre-authenticated request URL” as I mentioned in the README. Or use WSL. If I’ll reach Windows PC someday, I’ll definitely check, thanks for reporting this

**Comment by hitrov** [comment]
Sure you double quoted the path inside .env?

**Comment by elterrasense** [comment]
Tested using the pre-authenticated request URL on buckets, unfortunately I am now getting a different type of error:
![image](https://user-images.githubusercontent.com/19367314/151070429-e0282aa8-5061-48ff-8115-7a0c2d268920.png)

> Sure you double quoted the path inside .env?
Yes, both the path to the .pem file and the public key string.

**Comment by hitrov** [comment]
That’s common error on fresh dev env in Windows, just Google it

**Comment by elterrasense** [comment]
Alright I got it all working!

> That’s common error on fresh dev env in Windows, just Google it

Indeed, thanks for your time!
