### ISSUE TITLE
NotAuthorizedOrNotFound

### ISSUE THREAD

**Issue by s12321** [hitrov/oci-arm-host-capacity#2]
I following the instruction on a new setup, but end up to this error, does anyone have the same issue before? Thanks

php /var/www/html/oci-arm-host-capacity/index.php
: {
  "code" : "NotAuthorizedOrNotFound",
  "message" : "Authorization failed or requested resource not found."
}

base on: php7.4, composer 2.1.8

ps. Ampere still out of stock at this posting time, dont know how to get one.  :)

**Comment by hitrov** [comment]
Hi,
It tells exactly what it means,
Double check you didn’t mixed up arguments 
$config1 = new OciConfig(
    // region
    // user
    // tenancy
   // fingerprint
    // key_filename
    // availabilityDomain
    // subnetId
    // imageId
);

**Comment by s12321** [comment]
Thanks 👍  I added back the protocol "jYtI:" in front of the domain, it works now 💯

**Comment by fidelix** [comment]
This needs to be reopened.
I have `WSjO:SA-SAOPAULO-1-AD-1` in the domain, and also tried not specifying anything, and I get the same error.

**Comment by hitrov** [comment]
Hey, I believe not authorized error is not related anyhow to AD

**Comment by hitrov** [comment]
But you can try to use your auth data using official CLI tool https://hitrov.medium.com/resolving-oracle-cloud-out-of-capacity-issue-and-getting-free-vps-with-4-arm-cores-24gb-of-a3d7e6a027a8

**Comment by hitrov** [comment]
Also please keep in mind that now you don’t need to edit PHP files at all, pull the changes from repo and adjust only .env file (check updated README)

**Comment by fidelix** [comment]
> Also please keep in mind that now you don’t need to edit PHP files at all, pull the changes from repo and adjust only .env file (check updated README)

To clarify, I only edited the .env file, nothing else.

I used the official CLI as per your instructions and it worked (by that I mean I got the proper response "out of capacity").
Thanks for that. I still believe there is an issue somehow with the PHP request, though.

**Comment by hitrov** [comment]
Please reach me through Discord (link in the README) and sent PM with blurred .env

**Comment by hitrov** [comment]
Because we’re all interested to solve it both for you the other future users as well

**Comment by Mist-Hunter** [comment]
I had this same issue / error message. After doing things manually, I discovered that I somehow dropped the last character on the IOCI_MAGE_ID and the OCI_SUBNET_ID. With their length it was easy to miss on review. I still don't know how I did it. After adding the missing characters, I got the expected "out of capacity" error.

**Comment by hitrov** [comment]
Thanks for letting me know
