### ISSUE TITLE
Confuse with the ssh public key part

### ISSUE THREAD

**Issue by dsakura** [hitrov/oci-arm-host-capacity#23]
> OCI_SSH_PUBLIC_KEY (SSH access)
> In order to have secure shell (SSH) access to the instance you need to have a keypair, besically 2 files:
> 
> ~/.ssh/id_rsa
> ~/.ssh/id_rsa.pub
> Second one (public key) contents (string) should be provided to a command below. The are plenty of tutorials on how to generate them (if you don't have them yet), we won't cover this part here.
> 
> cat ~/.ssh/id_rsa.pub

First, many thanks!
Using putty I created the two key files. What do I do with them and where do I run the "cat" code and the relationship between the created keys is confusing to me.
Sorry, I'm not an expert, but I really need this, I'd be very grateful if you could help me. Thank you again.

**Comment by hitrov** [comment]
Hey. Check this part here https://youtu.be/uzAqgjElc64 this version is without .env file yet, part you’ll get the idea
