### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by zainulhasan** [hitrov/oci-arm-host-capacity#25]
Hello, Getting this error.

PHP Fatal error:  Uncaught Hitrov\OCI\Exception\SignerValidateException: URL is invalid: https://iaas.region=ap-mumbai-1.oraclecloud.com/20160918/instances/?compartmentId=ocid1.tenancy.oc1..aaaaaaaatbpoahojdpsvl7wdn6jxshgzldoqc273yohmm7dbch7ka in /home/zain/Desktop/oci-arm-host-capacity/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php:329
Stack trace:

**Comment by SavageTheUnicorn** [comment]
What was the solution for this?

**Comment by hitrov** [comment]
hey, URL is populated using template string `"https://$api.{$config->region}.oraclecloud.com/20160918"`. in your case first value is fine (`iaas`), second supposed to be `ap-mumbai-1` but it's taken together with region word and equal sign which means you didn't set `OCI_REGION` correctly in `.env` file

**Comment by SavageTheUnicorn** [comment]
Yea! I figured it out on my own a few days before you replied and I've finally got an instance again, thanks! Appreciate your time for replying too!
