### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by KAMLEGENDZ** [hitrov/oci-arm-host-capacity#26]
PHP Parse error:  syntax error, unexpected '$availabilityDomain' (T_VARIABLE), expecting ')' in /home/ubuntu/.oci/oci-arm-host-capacity/index.php on line 89

![image](https://user-images.githubusercontent.com/86577993/156370457-45a27b78-8a45-4706-bb7a-82c63f98dca5.png)

**Comment by hitrov** [comment]
hey, show me your `OCI_AVAILABILITY_DOMAIN` from `.env`

**Comment by KAMLEGENDZ** [comment]
![image](https://user-images.githubusercontent.com/86577993/156374831-921a1de8-5f4d-43a6-ab17-815b3cb90b86.png)

**Comment by KAMLEGENDZ** [comment]
its good but now i have this prob
![image](https://user-images.githubusercontent.com/86577993/156375765-5bb4ea02-7e47-40bb-be32-b684a94debac.png)

**Comment by hitrov** [comment]
I believe you didn't just run `composer install`

**Comment by KAMLEGENDZ** [comment]
![image](https://user-images.githubusercontent.com/86577993/156378021-05da8588-ad86-47e8-bf5a-2b15b0e9495b.png)

**Comment by KAMLEGENDZ** [comment]
and now

**Comment by hitrov** [comment]
I bet you didn’t read instruction carefully. Seems `.env` file is missing at all

**Comment by hitrov** [comment]
I'd suggest to watch my video - YouTube link is in the README. It a bit old - without .env file usage - but will give you general idea
