### ISSUE TITLE
use bootvolumeid and not image id

### ISSUE THREAD

**Issue by KAMLEGENDZ** [hitrov/oci-arm-host-capacity#29]
i want my script to use a boot volume and not an image how i do

**Comment by hitrov** [comment]
Just remove value for `OCI_IMAGE_ID` and set both `OCI_AVAILABILITY_DOMAIN` (if there’s more than one in your region) and `OCI_BOOT_VOLUME_ID` https://github.com/hitrov/oci-arm-host-capacity/blob/main/.env.example#L41

**Comment by KAMLEGENDZ** [comment]
why anything appear 
![image](https://user-images.githubusercontent.com/86577993/158815355-51b7885e-c7ad-49f6-98d2-cc637558abcc.png)
![image](https://user-images.githubusercontent.com/86577993/158815447-a3a77d1c-d2b8-4090-a0a2-ef3018983f6a.png)

**Comment by hitrov** [comment]
please revert any php file(s) and check the README - .env file is now used, no need to modify the code directly

**Comment by hitrov** [comment]
also remove images above containing bot api token and sensitive OCI information
