### ISSUE TITLE
Is this error message OK?

### ISSUE THREAD

**Issue by 3735943886** [hitrov/oci-arm-host-capacity#3]
Thank you for great script.
It has been passed about 2 weeks since script running with 10minute interval, but still no luck. 
I’m just wondering that this error messages is normal and shall I wait for more? 
Or something might be wrong and have to correct it to work?
Output message is attached below. Thank you. 
![E2224DF4-B53E-42CB-A20D-6D988096CC4F](https://user-images.githubusercontent.com/9522390/135539650-9803f108-d287-493b-8307-3adf26d196de.jpeg)

**Comment by hitrov** [comment]
Hey, you're right, that's expected.
Btw I believe you're getting totally the same response in the OCI console (browser), you can double check.

**Comment by hitrov** [comment]
Also you can iterate through three availability domains - for ARM they are all always free. I just don’t have time to improve the script. The chance will be 3 times bigger ;)

**Comment by 3735943886** [comment]
Thank you for prompt reply.
