### ISSUE TITLE
PHP Fatal error: Uncaught TypeError:

### ISSUE THREAD

**Issue by Xaman-ek** [hitrov/oci-arm-host-capacity#31]
I'm trying to get an ARM server through the script but I encountered this error:

```
PHP Fatal error:  Uncaught TypeError: Hitrov\OciConfig::__construct(): Argument #1 ($region) must be of type string, bool given, called in /home/test/oci-arm-host-capacity/index.php on line 35 and defined in /home/test/oci-arm-host-capacity/src/OciConfig.php:42

Stack trace:
#0 /home/test/oci-arm-host-capacity/index.php(35): Hitrov\OciConfig->__construct()
#1 {main}
  thrown in /home/test/oci-arm-host-capacity/src/OciConfig.php on line 42

```
I don't understand what the error is. The region that I put inside .env file is in the same format as what was given in the example. I also checked both index.php and OciConfig.php files but to no avail.

**Comment by sumersm7** [comment]
in ur .env OCI_REGION should be string

**Comment by hitrov** [comment]
Maybe you modified `.env.example` file, rename it to just `.env`
