### ISSUE TITLE
NotAuthorizedOrNotFound Authorization failed or requested resource not found

### ISSUE THREAD

**Issue by sumersm7** [hitrov/oci-arm-host-capacity#32]
PHP Fatal error:  Uncaught Hitrov\Exception\ApiCallException: {
    "code": "NotAuthorizedOrNotFound",
    "message": "Authorization failed or requested resource not found."
} in /home/ubuntu/oci-arm-host-capacity-main/src/HttpClient.php:42
Stack trace:
#0 /home/ubuntu/oci-arm-host-capacity-main/src/OciApi.php(218): Hitrov\HttpClient::getResponse()
#1 /home/ubuntu/oci-arm-host-capacity-main/src/OciApi.php(101): Hitrov\OciApi->call()
#2 /home/ubuntu/oci-arm-host-capacity-main/index.php(76): Hitrov\OciApi->getInstances()
#3 {main}
  thrown in /home/ubuntu/oci-arm-host-capacity-main/src/HttpClient.php on line 42

**Comment by hitrov** [comment]
OCI_REGION
OCI_USER_ID
OCI_TENANCY_ID
OCI_KEY_FINGERPRINT
OCI_PRIVATE_KEY_FILENAME
They are all used for authentication, having any of it incorrect will cause this kind of error

**Comment by sumersm7** [comment]
idk what i was doing wrong but i have to retry that step 2 more time. and its working now. thanks for ur reply and this awesome repo. do u have idea how long it take for capacity to restock

**Comment by hitrov** [comment]
Totally depends on the Oracle, region or when someone destroys the similar instance

**Comment by sumersm7** [comment]
thanks for your code , i got a machine with 2ocpu and 12gb ram 
but Always free TAG is not on the Instance on console

**Comment by sumersm7** [comment]
so i can have 2 X (2 OCPU 12Gb ram) free for each month , till offer last. as it a 30 days have 2880 hr?
thanks for replying to my dumb questions

**Comment by hitrov** [comment]
True unless you won’t exceed 200GB of boot/block volumes in total. No worries :)
