### ISSUE TITLE
Inactive tenancy?

### ISSUE THREAD

**Issue by sufnoobzac** [hitrov/oci-arm-host-capacity#36]
I've managed to successfully created ARM instance yesterday. But this morning I can't see my instance and it says 

"You don’t have permission to view these resources in this compartment. Try another compartment, or contact your administrator for help."

also my tenance became inactive. does oracle blocked my account? whats the reason?

**Comment by sufnoobzac** [comment]
I've tried to ask in live chat but they refused to answer about tenancy.. 

![tae](https://user-images.githubusercontent.com/15175579/168399098-c23bc887-5ebd-4a04-a32b-3667e30243e5.jpg)

**Comment by hitrov** [comment]
I was able to reach support through sales chat. Account suspension is common for unknown reasons, check Reddit. Usually it’s automated

**Comment by yusufpraditya** [comment]
where's oracle sales chat located?

**Comment by hitrov** [comment]
Somewhere here if I remember correctly https://www.oracle.com/cloud/free/ you can also try to write here oraclehelp_ww@oracle.com
