### ISSUE TITLE
PHP Fatal error:  Uncaught Hitrov\Exception\ApiCallException:

### ISSUE THREAD

**Issue by heroes1412** [hitrov/oci-arm-host-capacity#37]
i already set all params to .env file, but when run php index.php it warning:
PHP 7.4.16
PHP Fatal error:  Uncaught Hitrov\Exception\ApiCallException: {
    "code": "NotAuthenticated",
    "message": "The required information to complete authentication was not provided or was incorrect."
} in /tmp/oci-arm-host-capacity/src/HttpClient.php:42
Stack trace:
#0 /tmp/oci-arm-host-capacity/src/OciApi.php(210): Hitrov\HttpClient::getResponse()
#1 /tmp/oci-arm-host-capacity/src/OciApi.php(102): Hitrov\OciApi->call()
#2 /tmp/oci-arm-host-capacity/index.php(66): Hitrov\OciApi->getInstances()
#3 {main}
  thrown in /tmp/oci-arm-host-capacity/src/HttpClient.php on line 42

**Comment by heroes1412** [comment]
it is a simple task to get these pieces of information, but i dont know why that is incorrect @@

**Comment by hitrov** [comment]
Hard to say. Try using double quotes for all of them. Double check this part https://github.com/hitrov/oci-arm-host-capacity#private-key-issues make sure you’re able to `cat /home/user/privatekey.pem`

**Comment by heroes1412** [comment]
i already chmod 777 to the pem file and tried to wrap values with single quotes and double quotes, but still got same warning. it is so weird @@.

**Comment by heroes1412** [comment]
can you verify that the script can run with your API key information? @hitrov

**Comment by hitrov** [comment]
I re-run it just now. All good https://github.com/hitrov/oci-arm-host-capacity/runs/6607805332?check_suite_focus=true

**Comment by Trngd** [comment]
Hello, I have ran the script for around a week and this exact same error occured. It used to run flawlessly and now it just happened out of nowhere. I have not made changes to the script whatsoever, so are there any solutions to this?
