### ISSUE TITLE
Syntax Error Issue

### ISSUE THREAD

**Issue by TheNelston** [hitrov/oci-arm-host-capacity#38]
Hi, currently getting this issue:

`Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /Users/[name]/oci-arm-host-capacity/src/OciConfig.php on line 11`

Any fix? Everything is fine up to this point

**Comment by hitrov** [comment]
Probably php-curl extension is not installed. But you should have got this error when doing `composer install`

**Comment by hitrov** [comment]
https://github.com/hitrov/oci-arm-host-capacity#github-actions-workflows
