### ISSUE TITLE
Can not fine Vendor/autoload.php

### ISSUE THREAD

**Issue by afzl-wtu** [hitrov/oci-arm-host-capacity#4]
I encounter this error everytime :
![image](https://user-images.githubusercontent.com/64379149/147956086-4b2a467a-813a-42d3-9217-7a78fbc06576.png)

Here is line 8:
![image](https://user-images.githubusercontent.com/64379149/147955881-8fd4beb4-7d4f-471e-b482-b0b23ac279dc.png)

Even tried sudo command , apt-get updates but no use. There are files missing in your repo.

**Comment by hitrov** [comment]
Run https://github.com/hitrov/oci-arm-host-capacity/blob/main/README.md#installation `composer install` to put external dependencies in vendor directory

**Comment by afzl-wtu** [comment]
![image](https://user-images.githubusercontent.com/64379149/147956703-dca36b7d-5151-4c4f-983d-c1b324fdff0f.png)

**Comment by afzl-wtu** [comment]
> Run https://github.com/hitrov/oci-arm-host-capacity/blob/main/README.md#installation `composer install` to put external dependencies in vendor directory

Aleady installed

**Comment by afzl-wtu** [comment]
This is cloud vm with AMD micro processor.

**Comment by afzl-wtu** [comment]
Sorry my mistake Now:
![image](https://user-images.githubusercontent.com/64379149/147957125-ccb53a3c-4308-4dd8-a7a2-3c7a14a38f3b.png)
****

**Comment by hitrov** [comment]
Check my video, I’ve already solved similar issues for beginners https://youtu.be/uzAqgjElc64
