### ISSUE TITLE
add "START instance" function

### ISSUE THREAD

**Issue by heroes1412** [hitrov/oci-arm-host-capacity#41]
I accidentally power off 1 instance, now i cannot start it on :))
i think "start" current instance function is nice feature.

**Comment by hitrov** [comment]
you can terminate the instance, just make sure to preserve boot volume. then set it's `OCI_BOOT_VOLUME_ID` https://github.com/hitrov/oci-arm-host-capacity/blob/main/.env.example#L41 and launch the script as usual

**Comment by designboxcom** [comment]
Well, the proposed solution surely works well but I also would be very happy with an option to simply test and start an existing instance. Thus, I won't have to configure again IP addresses and SSH keys aso on a new instance... Hope it makes sense.
