### ISSUE TITLE
Discord Notification of Success

### ISSUE THREAD

**Issue by pewter77** [hitrov/oci-arm-host-capacity#42]
Because I didn't want to check forever, to get notified i setup a systemd process with the following script.
This is very hacky... in some circles. CHANGE THE DISCORD URL AND THE PATH TO YOUR OCI.LOG FROM THE GUIDE.

```
#!/bin/bash
$DISCORD_URL=https://discord.com/api/webhooks/123456789123456789/QWERTYUIOPASDFGHJKLZXCVBNM

curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"Script oracle restarting\"}" $DISCORD_URL

tail -fn0 /path/to/log/oci.log | \
while read line ; do
        echo "$line" | grep "LimitExceeded"
        if [ $? = 0 ]
        then
            curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"GOT IT!\"}" $DISCORD_URL
        fi
done
```

**Comment by hitrov** [comment]
Instead you can implement https://github.com/hitrov/oci-arm-host-capacity/blob/main/src/Interfaces/NotifierInterface.php#L9 and uncomment https://github.com/hitrov/oci-arm-host-capacity/blob/main/index.php#L91
