### ISSUE TITLE
Error executing Script: Argument #1 ($region) must be of type string, bool given

### ISSUE THREAD

**Issue by Rtchyc** [hitrov/oci-arm-host-capacity#45]
I have this error where I can't run the script

THE ERROR:

`PHP Fatal error: Uncaught TypeError: Hitrov\OciConfig::__construct(): Argument #1 ($region) must be of type string, bool given, called in C:\Users\NAME\Downloads\oci-arm-host-capacity\index.php on line 35 and defined in C:\Users\NAME\Downloads\oci-arm-host-capacity\src\OciConfig.php:42`

How can I solve?

IMG:
[IMG PRINT](https://ibb.co/hCCLSWF)

**Comment by hitrov** [comment]
Looks like you either haven’t run `composer install` or didn’t rename/fill `.env`

**Comment by Rtchyc** [comment]
> Parece que você não executou `composer install`ou não renomeou/preencheu`.env`

So I have to complete the .env and index.php with information?

**Comment by hitrov** [comment]
Only .env. Please check the README. YouTube video (if you watched one) is a bit outdated in that regards

**Comment by Rtchyc** [comment]
Got it, I think that's what complicated me, because I was watching the video on youtube, I'll try again by reading the README

**THANKS**
