### ISSUE TITLE
Does github action test still work ?

### ISSUE THREAD

**Issue by neilfromfuture** [hitrov/oci-arm-host-capacity#51]
I checked the Run Script expand but it just 1 log then nothing after that, I've checked every 10 minutes

**Comment by rasvanjaya21** [comment]
It same with me, just only there 1 log. Any solution ?

**Comment by neilfromfuture** [comment]
> It same with me, just only there 1 log. Any solution ?

yeah, same. Sadly there's no new update, and the first method only work is using local Linux machine or your own vps. I got one but delete it (cause I'm stupid) => don't have any 24 hours vps running anymore. But I'm using window rn not linux anymore cause I don't feel good. I've it running every 1 minutes from linux before and make a custom notify-send and sound and grep to check if the oci.log have "data" that the past now, don't how to setup on window yet but maybe the same and find some thing like cron job on window so it will run fine(I'm using 12 hours a day so it will be fine).

**Comment by rasvanjaya21** [comment]
edited : after waiting about 30 minutes, I got new log labeled "Scheduled", so the corn jobs is works fine, nothing problems, it's like delay. refer to GitHub Community discussion [No assurance on scheduled jobs](https://github.com/rasvanjaya21/oci-arm-host-capacity/actions/runs/3307331631/jobs/5458882453). but I change the schedule from 5 minutes to 10 minutes. so, this is not issue, please close it. thank you

**Comment by neilfromfuture** [comment]
> edited : after waiting about 30 minutes, I got new log labeled "Scheduled", so the corn jobs is works fine, nothing problems, it's like delay. refer to GitHub Community discussion [No assurance on scheduled jobs](https://github.com/rasvanjaya21/oci-arm-host-capacity/actions/runs/3307331631/jobs/5458882453). but I change the schedule from 5 minutes to 10 minutes. so, this is not issue, please close it. thank you

Oh so it logs in a different job, mine has like 200 of that workflows, damn. I think it's fine? Look like set it to 10 minutes will be fine because oracle not always have capacity. Well, I think I will closed this, thank u buddy, having someone have the same issue make thing clear.
