### ISSUE TITLE
Limit Exceeded

### ISSUE THREAD

**Issue by GabrielBigardi** [hitrov/oci-arm-host-capacity#55]
Hi, i've deleted my ARM/AMD instance and i got the "Out of capacity" when i was trying to create a new one, so i configured the script and it's been running for 3 days, however i got a different message today:

"code": "LimitExceeded"
"message": "The following service limits were exceeded: standard-a1-memory-count, standard-a1-memory-regional-count, standard-a1-core-count, standard-a1-core-regional-count. Request a service limit increase from the service limits page in the console. "

Why i'm getting this message ? The limit was not exceeded, when i go to the limits tab in the Oracle Cloud it clearly says that i'm using 0/24GB ram and 0/4 VCPU on ARM instances, and the boot size (150gb) is also not being exceeded, as free tiers can have up to 200gb total disk size...

**Comment by hitrov** [comment]
https://github.com/hitrov/oci-arm-host-capacity/issues/35#issuecomment-1124568961
