### ISSUE TITLE
"Already have an instance running" error

### ISSUE THREAD

**Issue by raszio** [hitrov/oci-arm-host-capacity#57]
Hello!

I have only one VM.Standard.A1.Flex 1 core OCPU, 2 GB already running on Oracle Cloud.

When I run `php ./index.php`, I am getting the following message:

`Already have an instance(s) [MY_INSTANCE_NAME] in state(s) (respectively) [RUNNING]. User: ocid1.user.oc1.xxxxxxxxxxxxxxxxxxxxxx`

I am far from reaching my Free Tier capacity. Is it possible they are limiting "Always Free Tier" to only 1 ARM instance?

**Comment by hitrov** [comment]
I’ll just leave a part from the README
```… check whether there're already existing instances with the same OCI_SHAPE, as well as number of them OCI_MAX_INSTANCES (you can safely adjust the last one if you wanna e.g. two VM.Standard.A1.Flex with 2/12 - 2 OCPUs and 12GB RAM - each).```
