### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class "Dotenv\Dotenv" not found

### ISSUE THREAD

**Issue by NgoGManh** [hitrov/oci-arm-host-capacity#58]
> PHP Fatal error:  Uncaught Error: Class "Dotenv\Dotenv" not found in /home/manhhyo/oci-arm-host-capacity/index.php:16
> Stack trace:
> 0 {main}
>   thrown in /home/manhhyo/oci-arm-host-capacity/index.php on line 16
> 

it happened when i use "php ./index.php".

kind regards

**Comment by hitrov** [comment]
Hey, you didn’t run `composer install`
