### ISSUE TITLE
Getting error "InvalidParameter"

### ISSUE THREAD

**Issue by GBT55** [hitrov/oci-arm-host-capacity#59]
```
{
    "code": "InvalidParameter",
    "message": "Shape VM.Standard.A1.Flex is not valid for image ocid1.image.oc1.eu-madrid-1.aaaaaaaadmbhyvjacmqd7dfj7sj6dylzinkizaw23tw4aozfw66rhepse45a."
}
```

What's wrong with this error?

**Comment by hitrov** [comment]
I bet you pickup up the image for different architecture e.g. x86_64

**Comment by hitrov** [comment]
Looks strange because error message doesn’t start with a capital letter. Please share your partial .env without sensitive information

**Comment by GBT55** [comment]
There you go @hitrov 
```
OCI_REGION=eu-madrid-1
OCI_USER_ID=ocid1.user.oc1..xxxxxxxxx
OCI_TENANCY_ID=ocid1.tenancy.oc1..xxxxxxx
OCI_KEY_FINGERPRINT=XX:XX:XX:XX

# absolute path (including directories) or direct public accessible URL
OCI_PRIVATE_KEY_FILENAME="/home/guille/oci/barrosoguillermo55@gmail.com_2023-02-21T08_30_47.190Z.pem"
OCI_SUBNET_ID=ocid1.subnet.oc1.eu-madrid-1.XXXXX
OCI_IMAGE_ID=ocid1.image.oc1.eu-madrid-1.aaaaaaaam62zmmwcyrbzulztabqwytnnrg53miugckofqxqfafvqd67xqgqq # Oracle-Linux-9.0-aarch64-2022.12.16-0

# Always free ARM: 1,2,3,4. Always free AMD x64: 1
OCI_OCPUS=4

# Always free ARM: 6,12,18,24. NB! Oracle Linux Cloud Developer Image requires minimum 8. Always free AMD x64: 1
OCI_MEMORY_IN_GBS=24

# Or "VM.Standard.E2.1.Micro" for Always free AMD x64
OCI_SHAPE=VM.Standard.A1.Flex
OCI_MAX_INSTANCES=1

# Your public key ~/.ssh/id_rsa.pub contents
# NB! No new lines / line endings allowed! Put inside double quotes
OCI_SSH_PUBLIC_KEY="ssh-rsa XXXXXX = guille@raspberrypi"

# Is now optional for ARM since Always Free ARMs can be created in any AD.
# ListAvailabilityDomains API call will be used for retrieval https://docs.oracle.com/en-us/iaas/api/#/en/identity/20160918/AvailabilityDomain/ListAvailabilityDomains
#
# NB! Always free AMD x64 instances should be created only in "main" (Always Free Eligible) AD,
# you must set it manually in this case!
#
# If you wanna specify more than one, set as a PHP array in OciConfig constructor (inside index.php file)
OCI_AVAILABILITY_DOMAIN=

# Optional. If not set, default value depends on OCI_IMAGE_ID will be used.
# Minimum is 47 for AMD x64 or 50 for ARM, maximum is 200 for Always Free accounts
OCI_BOOT_VOLUME_SIZE_IN_GBS=

# Optional. If set, will be used instead OCI_IMAGE_ID. Cannot be used together with OCI_BOOT_VOLUME_SIZE_IN_GBS.
# Open https://cloud.oracle.com/block-storage/boot-volumes, click non-used and copy it's OCID
# NB! You must specify OCI_AVAILABILITY_DOMAIN also as they should be located in the same one
OCI_BOOT_VOLUME_ID=

```

Also, just confirming that the error message does NOT start with a capital letter, it's not an errata
![image](https://user-images.githubusercontent.com/76950842/220410258-206cee7c-58bf-4e1e-a2da-297087c5b394.png)

**Comment by GBT55** [comment]
Still getting the same error

**Comment by hitrov** [comment]
Make sure you have this shape in the UI within every availability domain (AD). Otherwise specify it inside .env

**Comment by GBT55** [comment]
Yeah, Madrid only has one AD, so I think that's not the problem

**Comment by hitrov** [comment]
please paste a curl request from the browser (without auth headers)

**Comment by aarjo** [comment]
I'm having the same issue, I think it's because currently selecting Ampere shows no shapes available: 

![image](https://user-images.githubusercontent.com/7320403/220817639-9acedcd5-a6c4-4a1d-bcc8-2e536d125f8a.png)

I'm curious if once Ampere instances become available, the script will still work as long as you're using an OCI_IMAGE_ID that is compatible with Ampere?

**Comment by hitrov** [comment]
Thanks for the update. It should. Let’s see :)

**Comment by GBT55** [comment]
I posted the same thing on Reddit and 2 guys told me that Madrid, Spain region does not have nor has ever had Ampere instances available. Nor do we know if it will have at some point.

**Comment by aarjo** [comment]
I'm in the Chicago, US region which appears to have Ampere instances, just currently out of capacity.
https://www.reddit.com/r/oraclecloud/comments/112y6kd/no_ampere_shapes_showing_up_in_us_midwest_chicago/

**Comment by aarjo** [comment]
Actually, reading more into that reddit thread some recent comments suggest that Ampere isn't currently available in the US Midwest region.... woops

**Comment by crxssrazr93** [comment]
I am getting this error instead:

```
{
    "code": "InvalidParameter",
    "message": "Unable to parse message body"
}
```

**Comment by GBT55** [comment]
Confirmed. I have created an account in a different region, and I was able to create Ampere Instances with the script.
