### ISSUE TITLE
curl error occurred: OpenSSL SSL_connect

### ISSUE THREAD

**Issue by neilfranci** [hitrov/oci-arm-host-capacity#61]
The script print normal output like:
`{
    "code": "InternalError",
    "message": "Out of host capacity."
}`

but at some point it print out this instead?
`Fatal error: Uncaught Hitrov\Exception\CurlException: curl error occurred: OpenSSL SSL_connect: SSL_ERROR_ZERO_RETURN in connection to iaas.ap-singapore-1.oraclecloud.com:443 , response:  in /data/data/com.termux/files/home/oci-arm-host-capacity/src/HttpClient.php:31
Stack trace:
#0 /data/data/com.termux/files/home/oci-arm-host-capacity/src/OciApi.php(210): Hitrov\HttpClient::getResponse(Array)
#1 /data/data/com.termux/files/home/oci-arm-host-capacity/src/OciApi.php(102): Hitrov\OciApi->call(Object(Hitrov\OciConfig), 'https://iaas.ap...', 'GET', NULL, Array)
#2 /data/data/com.termux/files/home/oci-arm-host-capacity/index.php(66): Hitrov\OciApi->getInstances(Object(Hitrov\OciConfig))
#3 {main}
  thrown in /data/data/com.termux/files/home/oci-arm-host-capacity/src/HttpClient.php on line 31`

Not sure what I do wrong
`OCI_PRIVATE_KEY_FILENAME` is the `.pem` file get from API KEY

`OCI_SSH_PUBLIC_KEY` is the id_rsa.pub key in my `.ssh/ `folder

**Comment by hitrov** [comment]
Some kind of a network issue I suppose

**Comment by neilfranci** [comment]
> 

Yeah, maybe that.
