### ISSUE TITLE
Document required packages for installation

### ISSUE THREAD

**Issue by jl-678** [hitrov/oci-arm-host-capacity#63]
First, thank you for this app! It is awesome, and I am using it now. A challenge that I faced had when installing this was figuring out what packages (php and otherwise) were required. Not sure if it was because I was using a minimal build, but it would be great if you could list them in the instructions. Here is what I installed to make it work:

1. php-cli
2. libapache2-mod-php <-- I am not sure if this is needed
3. php-mbstring
4. php-mimetype
5. php-curl
6. [Composer](https://getcomposer.org/doc/00-intro.md)
7. unzip <- install with "apt install unzip"

**Comment by hitrov** [comment]
That’s a good point, I mentioned some of those in my video’s description https://youtu.be/uzAqgjElc64
