### ISSUE TITLE
PHP Fatal error: Uncaught Hitrov\Exception\CurlException

### ISSUE THREAD

**Issue by bbauti** [hitrov/oci-arm-host-capacity#65]
Hello! sometimes, randomly, I get this error:

> **PHP Fatal error:  Uncaught Hitrov\Exception\CurlException: curl error occurred: Resolving timed out after 10000 milliseconds, response:  in /home/bbauti/oci-arm-host-capacity/src/HttpClient.php:31
Stack trace:
#0 /home/bbauti/oci-arm-host-capacity/src/OciApi.php(210): Hitrov\HttpClient::getResponse()
#1 /home/bbauti/oci-arm-host-capacity/src/OciApi.php(102): Hitrov\OciApi->call()
#2 /home/bbauti/oci-arm-host-capacity/index.php(66): Hitrov\OciApi->getInstances()
#3 {main}
thrown in /home/bbauti/oci-arm-host-capacity/src/HttpClient.php on line 31**

it appears randomly in between the "Out of host capacity" errors

**Comment by hitrov** [comment]
I believe it’s straightforward network issue :)
