### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by B1n00** [hitrov/oci-arm-host-capacity#7]
Hello,

I just tried to launch the script and it result in a PHP Parse error on Line 75. 
it seems to be caused by the $availabilityDomainEntity[‘Name’]

**Comment by hitrov** [comment]
Hey, thanks for your comment, I resolved this yesterday https://github.com/hitrov/oci-arm-host-capacity/commit/77786fc8fae93cb842dcd4b94cf144c09b6e9459 you can update the code by running `git pull origin main`

**Comment by B1n00** [comment]
I have this version but it is resulting with the following error:
`PHP Parse error:  syntax error, unexpected 'name' (T_STRING) in /home/binoo/oci-arm-host-capacity/index.php on line 75`

**Comment by hitrov** [comment]
which value of availability domain do you have on line 29?
if you use env vars, what's the value of `OCI_AVAILABILITY_DOMAIN`?

**Comment by hitrov** [comment]
I have no value set, see how it works: https://github.com/hitrov/oci-arm-host-capacity/runs/4737188301?check_suite_focus=true (please expand `run script`)

**Comment by hitrov** [comment]
let me also try with string value set

**Comment by hitrov** [comment]
here's https://github.com/hitrov/oci-arm-host-capacity/runs/4737211106?check_suite_focus=true and it's commit https://github.com/hitrov/oci-arm-host-capacity/commit/ab7352a95d7a457f6064c428a5f9a1cb3d2a5595

**Comment by hitrov** [comment]
and with array value https://github.com/hitrov/oci-arm-host-capacity/commit/d3661238fd7435edc649d7b3beda47a4b271288b https://github.com/hitrov/oci-arm-host-capacity/runs/4737229830?check_suite_focus=true

**Comment by hitrov** [comment]
Empty string https://github.com/hitrov/oci-arm-host-capacity/commit/15ff891c9543c19e12de2a7d7c492e4b6ebcebea https://github.com/hitrov/oci-arm-host-capacity/runs/4737244184?check_suite_focus=true

**Comment by hitrov** [comment]
I'd suggest to execute `git diff` to compare this line with base branch. or better copy your string values somewhere temporary and `git checkout main` then replace them again

**Comment by hitrov** [comment]
actually any IDE must highlight syntax error for you

**Comment by B1n00** [comment]
Here is the result of the git diff (I just remove some parts of the various variable). Nothing seem strange IMO

```
-    getenv('OCI_REGION') ?: 'us-phoenix-1', // region
-    getenv('OCI_USER_ID') ?: 'ocid1.user.oc1..aaaaaaaa***', // user
-    getenv('OCI_TENANCY_ID') ?: 'ocid1.tenancy.oc1..aaaaaaaaa***', // tenancy
-    getenv('OCI_KEY_FINGERPRINT') ?: '42:b1:***:5b:2c', // fingerprint
-    getenv('OCI_PRIVATE_KEY_FILENAME') ?: "oracleidentitycloudservice_oracle-***.pem", // key_file
-    getenv('OCI_AVAILABILITY_DOMAIN') ?: null, // availabilityDomain(s): null or '' or 'jYtI:PHX-AD-1' or ['jYtI:PHX-AD-1','jYtI:PHX-AD-2']
-    getenv('OCI_SUBNET_ID') ?: 'ocid1.subnet.oc1.phx.aaaaaaaa***', // subnetId
-    getenv('OCI_IMAGE_ID') ?: 'ocid1.image.oc1.phx.aaaaaaaay***', // imageId_
+    getenv('OCI_REGION') ?: 'eu-marseille-1', // region
+    getenv('OCI_USER_ID') ?: 'ocid1.user.oc1..aaaaaaaayosv6a', // user
+    getenv('OCI_TENANCY_ID') ?: 'ocid1.tenancy.oc1..aaaaaaaalhcd55yv2tielesd4dj4yllsa', // tenancy
+    getenv('OCI_KEY_FINGERPRINT') ?: '4d:68:b5:38:31:9b1:96:22', // fingerprint
+    getenv('OCI_PRIVATE_KEY_FILENAME') ?: "oracleidentitycloudservice_binoo972-01-06-21-00.pem", // key_file
+    getenv('OCI_AVAILABILITY_DOMAIN') ?: 'gTce:EU-MARSEILLE-1-AD-1', // availabilityDomain(s): null or '' or 'gTce:EU-MARSEILLE-1-AD-1'
+    getenv('OCI_SUBNET_ID') ?: 'ocid1.subnet.oc1.eu-marseille-1.aaaaaaaahy4svu7scl4db6wsujb7bbcuhx6zztv36ijkhd6mvq4ktcmrkcnq', // subnetId
+    getenv('OCI_IMAGE_ID') ?: 'ocid1.image.oc1.eu-marseille-1.aaaaaaaaoygutjey3po3dwskuov5wr2t7rz7oiwscnwentxlt6fk4jknpylq', // imageId**
```

```
-    $sshKey = getenv('OCI_SSH_PUBLIC_KEY') ?: 'ssh-rsa AAAAB3NzaC1...p5m8= ubuntu@localhost'; // ~/.ssh/id_rsa.pub contents
+    $sshKey = getenv('OCI_SSH_PUBLIC_KEY') ?: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQX$
```

**Comment by hitrov** [comment]
I wonder how did you set all the values starting from `OCI_REGION` and up to `OCI_SSH_PUBLIC_KEY`
