### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by gabrielflachssa** [hitrov/oci-arm-host-capacity#73]
PHP Fatal error:  Uncaught Hitrov\Exception\ApiCallException: {
    "code": "NotAuthenticated",
    "message": "Date 'Wed, 26 Apr 2023 13:08:43 UTC' is not within allowed clock skew. Current 'Wed, 26 Apr 2023 14:23:55 UTC', valid datetime range: ['Wed, 26 Apr 2023 14:18:55 UTC', 'Wed, 26 Apr 2023 14:28:56 UTC']"
} in /home/suporte/oci-arm-host-capacity/src/HttpClient.php:42
Stack trace:
#0 /home/suporte/oci-arm-host-capacity/src/OciApi.php(257): Hitrov\HttpClient::getResponse()
#1 /home/suporte/oci-arm-host-capacity/src/OciApi.php(132): Hitrov\OciApi->call()
#2 /home/suporte/oci-arm-host-capacity/index.php(74): Hitrov\OciApi->getInstances()
#3 {main}
  thrown in /home/suporte/oci-arm-host-capacity/src/HttpClient.php on line 42

How can I solve this error, please?

**Comment by hitrov** [comment]
hey, seems your system clock are incorrect

**Comment by gabrielflachssa** [comment]
Thanks for reply.

The error is a timesyncd on raspberry not sync time with the ntp server.
