### ISSUE TITLE
NotAuthorizedOrNotFound

### ISSUE THREAD

**Issue by notabhixhek** [hitrov/oci-arm-host-capacity#80]
![Screenshot 2023-05-06 194522](https://user-images.githubusercontent.com/95033966/236629512-522d40e7-ff9f-4a8b-b5c7-32388ee83ccc.png)
Any Idea on how to fix this issue?

**Comment by PlyfexHD** [comment]
I think maybe you put in some wrong public key or wrong private api key in.

**Comment by notabhixhek** [comment]
everything looks fine
