### ISSUE TITLE
Is this script still works 4 Core with 24GB ram?

### ISSUE THREAD

**Issue by writingdeveloper** [hitrov/oci-arm-host-capacity#9]
First of all, thanks for the developing this script. I got a new Oracle Instance.

But I just want to know is this script still works if I set to 4 Core with 24GB ram.

About 2 weeks ago, I run this script on my server, but it seems it only shows the 'Out of host limit' message.

And someone replied that it works with 3 Core with 18GB ram. So I tried with this settings and now it works well.

Still, 3 Core and 18GB instance is big enough but I just want to know is this still works 4 core and 24GB ram.

**Comment by hitrov** [comment]
Hey, you’re welcome!
If you have Free Tier only account, you must destroy our 3/18.
Of course, it works with 4/24 as it’s said in README, but availability depends only on Oracle’s side…
