### ISSUE TITLE
What can I do to fix this?

### ISSUE THREAD

**Issue by decode2** [hitrov/oci-arm-host-capacity#92]
PHP Fatal error:  Uncaught Hitrov\Exception\CurlException: curl error occurred: error setting certificate file: C:/Users/Matias/oci-arm-host-capacity/name_2023-07-29T02_46_46.003Z.pem, response:  in C:\Users\Matias\oci-arm-host-capacity\src\HttpClient.php:31
Stack trace:
#0 C:\Users\Matias\oci-arm-host-capacity\src\OciApi.php(257): Hitrov\HttpClient::getResponse()
#1 C:\Users\Matias\oci-arm-host-capacity\src\OciApi.php(132): Hitrov\OciApi->call()
#2 C:\Users\Matias\oci-arm-host-capacity\index.php(74): Hitrov\OciApi->getInstances()
#3 {main}
  thrown in C:\Users\Matias\oci-arm-host-capacity\src\HttpClient.php on line 31

I'm completely new to php and because of this project, can someone help me fix this?

**Comment by hitrov** [comment]
https://www.google.com/search?q=curl+error+occurred%3A+error+setting+certificate+file
