### ISSUE TITLE
shape VM.Standard.A1.Flex not found

### ISSUE THREAD

**Issue by SahajJain01** [hitrov/oci-arm-host-capacity#96]
{
    "code": "NotAuthorizedOrNotFound",
    "message": "shape VM.Standard.A1.Flex not found"
}

Getting this in my logs recently.

**Comment by hitrov** [comment]
please make sure you're able to create it using browser UI and send me JSON request payload, maybe they did change name to something different than `VM.Standard.A1.Flex`

**Comment by SahajJain01** [comment]
I'm not able to create it via browser UI as well now. Earlier have been able to and the logs were also giving Out of capacity error.
![image](https://github.com/hitrov/oci-arm-host-capacity/assets/14031504/1318ea74-ad60-479b-bdb0-a4020cf632c0)

**Comment by hitrov** [comment]
I added script to check shapes, but cannot tell when I gonna merge it to main just yet https://github.com/hitrov/oci-arm-host-capacity/blob/check-shapes/shapes.php
